Repository 9oormthon-project3-team2/Friendchise-frontend, pull requests merged in 2025-02, with the labels that each got.

#9 알림 기본 화면 구현
  package-lock.json
  src/App.js
  src/hooks/useSSE.js
  src/pages/NotificationPage.js
Labels: feat

#14 Feat/sse connection to receive realtime notifications
  package-lock.json
  package.json
  src/hooks/useSSE.js
  src/pages/NotificationPage.js
Labels: feat, enhancement

#20 Feat/mypage notification
  src/pages/MyPage.js
Labels: feat

#19 알림 읽기 및 삭제 기능 추가
  src/hooks/useSSE.js
  src/pages/NotificationPage.js
Labels: feat

#26 Feat/sse connection store manager logined
  src/App.js
  src/components/SSEManager.js
  src/context/NotificationsContext.js
  src/pages/NotificationPage.js
Labels: feat, enhancement

#27 [Feature] 매장에 대한 화면 구현
  package.json
  src/App.js
  src/pages/MyPage.js
  src/pages/store/AddressSearchModal.js
  src/pages/store/CreateStore.js
  src/pages/store/UpdateStore.js
Labels: feat, wontfix, refactor

#31 [Feature] 매장에 대한 화면 구현
  src/App.js
Labels: bug

#30 본사 마이페이지 변경
  src/pages/MyPage.js
Labels: feat

#32 파라미터 불일치 수정 및 알림 읽음/삭제 시 토스트 팝업 추가
  package-lock.json
  package.json
  src/pages/NotificationPage.js
Labels: bug, feat

#38 Refactor/매니저 엔드포인트 수정
  src/App.js
  src/components/SSEManager.js
  src/pages/LoginPage.js
  src/pages/MemberSearch.js
  src/pages/store/UpdateStore.js
Labels: refactor
